# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fibonacci.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ibonacci.proto\"\x1d\n\x10\x46ibonacciRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"#\n\x11\x46ibonacciResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32T\n\x13\x46ibonacciCalculator\x12=\n\x12\x43\x61lculateFibonacci\x12\x11.FibonacciRequest\x1a\x12.FibonacciResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fibonacci_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIBONACCIREQUEST._serialized_start=19
  _FIBONACCIREQUEST._serialized_end=48
  _FIBONACCIRESPONSE._serialized_start=50
  _FIBONACCIRESPONSE._serialized_end=85
  _FIBONACCICALCULATOR._serialized_start=87
  _FIBONACCICALCULATOR._serialized_end=171
# @@protoc_insertion_point(module_scope)
