# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fibonacci_pb2 as fibonacci__pb2


class FibonacciCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateFibonacci = channel.unary_unary(
                '/FibonacciCalculator/CalculateFibonacci',
                request_serializer=fibonacci__pb2.FibonacciRequest.SerializeToString,
                response_deserializer=fibonacci__pb2.FibonacciResponse.FromString,
                )


class FibonacciCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateFibonacci(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FibonacciCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateFibonacci': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateFibonacci,
                    request_deserializer=fibonacci__pb2.FibonacciRequest.FromString,
                    response_serializer=fibonacci__pb2.FibonacciResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FibonacciCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FibonacciCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateFibonacci(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FibonacciCalculator/CalculateFibonacci',
            fibonacci__pb2.FibonacciRequest.SerializeToString,
            fibonacci__pb2.FibonacciResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
